### ISSUE TITLE
Wiki: Kommentar Marie (2)

### ISSUE THREAD

**Issue by marie-stueger** [chpollin/PM_DHGraz#4]
Ich kann in diesem [Eintrag](https://github.com/chpollin/PM_DHGraz/wiki/Was-ist-ein-Projektstrukturplan%3F-Mini-Beispiel-eines-Projektstrukturplanes) die "phasenorientierter PSP" Grafik nicht sehen. Ich denke, da funktioniert der Link nicht richtig.

**Comment by 0815Username** [comment]
Danke für den Hinweis, bei mir war die Grafik angezeigt. Vielleicht lag es an der Berechtigung zum verlinkten repository, dass andere die Grafik nicht sehen konnten. Habe in einem ersten Lösungsversuch die Berechtigung geändert. Bitte um Rückmeldung.

**Comment by marie-stueger** [comment]
Jetzt funktioniert alles! Ich hatte lustigerweise das gleiche Problem bei meinen Einträgen. Wär mir gar nicht aufgefallen, wenn ichs bei dir nicht gesehen hätte.

**Comment by 0815Username** [comment]
Ausgezeichnet. Danke! :)
